---
title: 
author: 
date: 
output: 
  word_document:
    reference_docx: landscape_reference.docx
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = F, message = F}
# Appendix 1
# Clean citation list 
library(tidyverse)

# Connecting the 2 data sheets 
tur_raw <- read_csv(here::here("data/ranking data.csv")) %>% 
  select(Strata:`Usefulness tier`)
tur_over <- read_csv(here::here("data/turkey demographics paper overview.csv")) %>%
  select(ID, Strata, "Publication Year", Years, Subspecies, Season, State)

# Break up the year ranges ####

# Combine them
apx1 <- left_join(tur_raw, tur_over, by = "Strata") %>% 
  mutate(
    gyvr = !grepl("-", .$Year) & !is.na(Year), # keep raw year if it's a single year
    gyover = !is.na(Years),
    plotyr = case_when(
      gyvr == T ~ Year,
      gyvr == F & gyover == T ~ Years # otherwise NA
    )
  ) %>%
  mutate(Year = plotyr) %>% 
  rename(citation = "Strata", 
         vitalrate = "Vital Rate",
         lifestage = "Life Stage",
         # error = "Error Measurment",
         comments = "Parameter Comments",
         pubyr = "Publication Year") %>% 
  select(vitalrate, period, lifestage, Sex, Parameter, SE, SD, CIwidth, #error,
         LCL, UCL, n,  
         citation, pubyr, Year, Subspecies, State) %>% 
  mutate(lifestage = replace(lifestage, 
                             lifestage == "Adult" | lifestage == "adults",
                             "adult"),
         vitalrate = replace(vitalrate, vitalrate == "nest suvival", "nest survival")
  ) %>%
  # Turn mortality into survival 
  mutate(Parameter = replace(Parameter, vitalrate == "annual mortality", 1-Parameter[vitalrate == "annual mortality"]),
         vitalrate = replace(vitalrate, vitalrate == "annual mortality", "annual survival"),
  ) %>%
  # Rename my vital rates and create appropriate periods
  mutate(
    periodinfo = period,
    period = case_when(
      vitalrate == "annual survival" ~ "annual",
      vitalrate == "seasonal survival" ~ "seasonal",
      vitalrate == "Nesting Season survival (DSR)" ~ "daily",
      vitalrate == "post-nesting survival (DSR)" ~ "daily",
      vitalrate == "poult survival" ~ "seasonal",
      vitalrate == "poult survival to November (DSR)" ~ "daily",
      vitalrate %in% 
        c("brood success", "clutch size", "hatching rate", 
          "natality rate", "nest DSR", "nest success", "nest survival",
          "nesting rate") ~ "first nest",
      vitalrate %in% 
        c("renest clutch size", "renest DSR", "renest hatching rate", 
          "renest success", "renest survival", "renesting rate") ~ "second nest", 
      vitalrate %in% c("third nest rate", "third nest success")~ "third nest",
      vitalrate == "recruitment rate" ~ "annual"
    ),
    vitalrate = case_when(
      vitalrate == "annual survival" ~ "survival",
      vitalrate == "seasonal survival"~ "survival",
      vitalrate == "Nesting Season survival (DSR)" ~ "survival",
      vitalrate == "post-nesting survival (DSR)" ~ "survival",
      vitalrate == "poult survival to November (DSR)" ~ "poult survival",
      vitalrate == "renest clutch size" ~ "clutch size",
      vitalrate == "renest DSR" ~ "nest DSR",
      vitalrate == "renest hatching rate" ~ "hatching rate",
      vitalrate == "renest success" ~ "nest success",
      vitalrate == "renest survival" ~ 'nest survival',
      vitalrate == "renesting rate" ~ "nesting rate",
      vitalrate == "third nest rate" ~ "nesting rate",
      vitalrate == "third nest success" ~ "nest success",
      # Then all the others I don't want to change 
      vitalrate == "brood success" ~ "brood success",
      vitalrate == "clutch size" ~ "clutch size",
      vitalrate == "hatching rate" ~ "hatching rate",
      vitalrate == "natality rate" ~ "natality rate",
      vitalrate == "nest DSR" ~ "nest DSR",
      vitalrate == "nest success" ~ "nest success",
      vitalrate == "nest survival" ~ "nest survival",
      vitalrate == "nesting rate" ~ "nesting rate",
      vitalrate == "poult survival" ~ "poult survival",
      vitalrate == "recruitment rate" ~ "recruitment rate"
    )
  ) 

# Fix rates recorded as percentages 
# "Rates" only excludes clutch size, natality rate and recruitment rate (which might be a rate?)
rateparams <- c("brood success", "hatching rate", "nest DSR", 
                "nest success", "nest survival", "nesting rate", "poult survival", 
                "survival"
)
p1 <- apx1 %>% 
  filter(vitalrate %in% rateparams & 
           (Parameter < 0 | Parameter > 1)) %>% 
  mutate(Parameter = Parameter/100)

apx1 %>% 
  # Put them back together
  filter(!(vitalrate %in% rateparams & 
            (Parameter < 0 | Parameter > 1)) ) %>% 
  bind_rows(., p1) %>% 
  # Organize
  select(citation, vitalrate, lifestage, Sex, Parameter, SE, n, SD, LCL, UCL, 
         CIwidth, Subspecies, State, Year, period, periodinfo) %>%
  rename(Citation = citation, `Vital Rate` = vitalrate, `Life Stage` = lifestage, `CI width` = CIwidth, Period = period, Info = periodinfo) %>% 
  mutate(Year = gsub("(\\d)-(\\d)", "\\1 - \\2", Year),
         Year = gsub("(\\d);(\\d)", "\\1; \\2", Year),
         Parameter = round(Parameter, 3)) %>% 
  knitr::kable()

```

